export const ROUTES = {
  home: "/",
  public: {
    home: "/",
    product: "/how-it-works",
    demo: "/demo",
    solutions: "/solutions",
    pricing: "/pricing",
    faq: "/faq",
    company: "/about",
    register: "/register",
  },
  auth: {
    login: "/bo/login",
  },
  bo: {
    root: "/bo",
    dashboard: "/bo/dashboard",
    tenants: "/bo/tenants",
    tenant: (id: string) => `/bo/tenants/${id}`,
    registrations: "/bo/registrations",
    registration: (id: string) => `/bo/registrations/${id}`,
    plans: "/bo/plans",
    planCreate: "/bo/plans/new",
    planEdit: (id: string) => `/bo/plans/${id}/edit`,
    subscriptions: "/bo/subscriptions",
    aiSettings: "/bo/ai-settings",
    usage: "/bo/usage",
    whatsapp: "/bo/whatsapp",
    messages: "/bo/messages",
    billing: "/bo/billing",
    profile: "/bo/profile",
    system: "/bo/system",
    auditLogs: "/bo/audit-logs",
  },
  api: {
    health: "/api/health",
    aiConfig: "/api/ai-config",
    plans: "/api/plans",
    plan: (id: string) => `/api/plans/${id}`,
    tenants: "/api/tenants",
    tenant: (id: string) => `/api/tenants/${id}`,
    tenantStatus: (id: string) => `/api/tenants/${id}/status`,
  },
} as const;
