import "server-only";

import { Client } from "pg";

import {
  migrateTenantDatabase,
  TENANT_SCHEMA_VERSION,
  type MigrationOutcome,
} from "@/server/tenancy/migrate-tenant-database";

/**
 * Tenant schema version applied by {@link provisionTenantDatabase}.
 *
 * Owned by the migration list now, and re-exported here because that is where
 * the rest of the application already imports it from.
 */
export { TENANT_SCHEMA_VERSION };

/** Maintenance database to connect to while creating another one. */
const MAINTENANCE_DATABASE = "postgres";

export type ProvisionDatabaseOutcome =
  | {
      readonly ok: true;
      readonly created: boolean;
      /**
       * The version this database actually reached, which is not always the
       * newest one: a migration whose extension the server does not have is
       * skipped, so the recorded version is what is true rather than what was
       * hoped for.
       */
      readonly version: string | null;
      readonly skipped: readonly string[];
    }
  | { readonly ok: false; readonly reason: string };

/**
 * Creates a tenant's physical database and applies the tenant schema.
 *
 * This is the one place in the application that talks to Postgres as an
 * administrator rather than as the application. It runs on the *master*
 * server's credentials, which is what makes it able to create a database at
 * all — and why it is deliberately the only module that reads them for this
 * purpose.
 *
 * `CREATE DATABASE` cannot run inside a transaction and cannot run from a
 * connection to the database being created, so this connects to the
 * maintenance database first, then reconnects to the new one to apply the
 * schema. That means the two steps are not atomic: a failure between them
 * leaves an empty database, which the schema step is written to recover from
 * on the next attempt rather than to trip over.
 *
 * In development the tenant databases live on the same server as the master,
 * under the same credentials. A production deployment would point
 * `TENANT_PROVISIONER_DATABASE_URL` at a dedicated server with an account that
 * can create databases and nothing else.
 */
export async function provisionTenantDatabase(
  databaseName: string,
): Promise<ProvisionDatabaseOutcome> {
  if (!isSafeDatabaseName(databaseName)) {
    return { ok: false, reason: `Unsafe database name "${databaseName}".` };
  }

  const adminUrl =
    process.env.TENANT_PROVISIONER_DATABASE_URL ?? process.env.DATABASE_URL;

  if (!adminUrl) {
    return { ok: false, reason: "No provisioner connection is configured." };
  }

  let created = false;

  try {
    created = await createDatabase(adminUrl, databaseName);
    const migrated = await applySchema(adminUrl, databaseName);

    return {
      ok: true,
      created,
      version: migrated.version,
      skipped: migrated.skipped.map((entry) => entry.version),
    };
  } catch (error: unknown) {
    // Never surface the driver error verbatim: it can echo the connection
    // string, credentials included.
    const detail = error instanceof Error ? error.message : "unknown error";
    console.error(
      `Tenant database provisioning failed for "${databaseName}".`,
      detail,
    );
    return { ok: false, reason: detail };
  }
}

/**
 * Guards the one place an identifier reaches SQL as text.
 *
 * `CREATE DATABASE` takes no parameters, so the name is interpolated. It is
 * generated by `deriveDatabaseName` and never user input, but this is the wrong
 * place to rely on that holding forever.
 */
function isSafeDatabaseName(name: string): boolean {
  return /^[a-z_][a-z0-9_]{0,62}$/.test(name);
}

/** True when the database was created, false when it already existed. */
async function createDatabase(
  adminUrl: string,
  databaseName: string,
): Promise<boolean> {
  const client = new Client({
    connectionString: withDatabase(adminUrl, MAINTENANCE_DATABASE),
    connectionTimeoutMillis: 10_000,
  });

  await client.connect();

  try {
    const existing = await client.query(
      "SELECT 1 FROM pg_database WHERE datname = $1",
      [databaseName],
    );

    if (existing.rowCount !== 0) return false;

    // Identifier quoting, not value quoting: the name passed isSafeDatabaseName
    // above, so the quotes are belt to that braces.
    await client.query(`CREATE DATABASE "${databaseName}"`);
    return true;
  } finally {
    await client.end().catch(() => undefined);
  }
}

/**
 * Brings the tenant database up to the current schema.
 *
 * Formerly applied one create-script and refused a database at any other
 * version. It now runs whatever migrations that database has not had, which is
 * what makes a schema change possible without dropping tenants who have data.
 */
async function applySchema(
  adminUrl: string,
  databaseName: string,
): Promise<MigrationOutcome> {
  const client = new Client({
    connectionString: withDatabase(adminUrl, databaseName),
    connectionTimeoutMillis: 10_000,
  });

  await client.connect();

  try {
    const outcome = await migrateTenantDatabase(client);

    for (const entry of outcome.skipped) {
      console.warn(
        `Tenant database ${databaseName}: migration ${entry.version} skipped — ${entry.reason}.`,
      );
    }

    return outcome;
  } finally {
    await client.end().catch(() => undefined);
  }
}

/**
 * Where a provisioned tenant database actually is.
 *
 * `tenant_databases` stores pointers, never credentials (S-03), but a pointer
 * has to point somewhere real: until the database existed, the row held
 * placeholder text like "pending/us-east-1/acme" and no connection could be
 * opened from it. These are the coordinates of the database this module just
 * created.
 */
export interface ProvisionedConnection {
  readonly host: string;
  readonly port: number;
  readonly username: string;
}

export function provisionedConnection(): ProvisionedConnection | null {
  const adminUrl =
    process.env.TENANT_PROVISIONER_DATABASE_URL ?? process.env.DATABASE_URL;

  if (!adminUrl) return null;

  try {
    const url = new URL(adminUrl);

    return {
      host: url.hostname,
      port: url.port === "" ? 5432 : Number(url.port),
      username: decodeURIComponent(url.username),
    };
  } catch {
    return null;
  }
}

/** Swaps the database name in a connection string, preserving everything else. */
function withDatabase(connectionString: string, databaseName: string): string {
  const url = new URL(connectionString);
  url.pathname = `/${databaseName}`;
  return url.toString();
}
