import "server-only";

import { readFile } from "node:fs/promises";
import path from "node:path";

import { Client } from "pg";

/**
 * Tenant schema version applied by {@link provisionTenantDatabase}.
 *
 * Must match the version `src/server/tenancy/schema/001_initial.sql` inserts
 * into `schema_migrations`, which is transcribed from
 * `docs/db/SaaS Tenant DB — Business + Storefront + AI + WhatsApp.png`.
 */
export const TENANT_SCHEMA_VERSION = "2026.09.3";

/** Maintenance database to connect to while creating another one. */
const MAINTENANCE_DATABASE = "postgres";

export type ProvisionDatabaseOutcome =
  | { readonly ok: true; readonly created: boolean }
  | { readonly ok: false; readonly reason: string };

/**
 * Creates a tenant's physical database and applies the tenant schema.
 *
 * This is the one place in the application that talks to Postgres as an
 * administrator rather than as the application. It runs on the *master*
 * server's credentials, which is what makes it able to create a database at
 * all — and why it is deliberately the only module that reads them for this
 * purpose.
 *
 * `CREATE DATABASE` cannot run inside a transaction and cannot run from a
 * connection to the database being created, so this connects to the
 * maintenance database first, then reconnects to the new one to apply the
 * schema. That means the two steps are not atomic: a failure between them
 * leaves an empty database, which the schema step is written to recover from
 * on the next attempt rather than to trip over.
 *
 * In development the tenant databases live on the same server as the master,
 * under the same credentials. A production deployment would point
 * `TENANT_PROVISIONER_DATABASE_URL` at a dedicated server with an account that
 * can create databases and nothing else.
 */
export async function provisionTenantDatabase(
  databaseName: string,
): Promise<ProvisionDatabaseOutcome> {
  if (!isSafeDatabaseName(databaseName)) {
    return { ok: false, reason: `Unsafe database name "${databaseName}".` };
  }

  const adminUrl =
    process.env.TENANT_PROVISIONER_DATABASE_URL ?? process.env.DATABASE_URL;

  if (!adminUrl) {
    return { ok: false, reason: "No provisioner connection is configured." };
  }

  let created = false;

  try {
    created = await createDatabase(adminUrl, databaseName);
    await applySchema(adminUrl, databaseName);
    return { ok: true, created };
  } catch (error: unknown) {
    // Never surface the driver error verbatim: it can echo the connection
    // string, credentials included.
    const detail = error instanceof Error ? error.message : "unknown error";
    console.error(
      `Tenant database provisioning failed for "${databaseName}".`,
      detail,
    );
    return { ok: false, reason: detail };
  }
}

/**
 * Guards the one place an identifier reaches SQL as text.
 *
 * `CREATE DATABASE` takes no parameters, so the name is interpolated. It is
 * generated by `deriveDatabaseName` and never user input, but this is the wrong
 * place to rely on that holding forever.
 */
function isSafeDatabaseName(name: string): boolean {
  return /^[a-z_][a-z0-9_]{0,62}$/.test(name);
}

/** True when the database was created, false when it already existed. */
async function createDatabase(
  adminUrl: string,
  databaseName: string,
): Promise<boolean> {
  const client = new Client({
    connectionString: withDatabase(adminUrl, MAINTENANCE_DATABASE),
    connectionTimeoutMillis: 10_000,
  });

  await client.connect();

  try {
    const existing = await client.query(
      "SELECT 1 FROM pg_database WHERE datname = $1",
      [databaseName],
    );

    if (existing.rowCount !== 0) return false;

    // Identifier quoting, not value quoting: the name passed isSafeDatabaseName
    // above, so the quotes are belt to that braces.
    await client.query(`CREATE DATABASE "${databaseName}"`);
    return true;
  } finally {
    await client.end().catch(() => undefined);
  }
}

/**
 * Applies the tenant schema, unless this database already has it.
 *
 * The SQL is generated by Prisma and uses plain `CREATE TABLE`, so running it
 * twice fails. Rather than weaken every statement to IF NOT EXISTS — which
 * would silently accept a half-built database as finished — the version marker
 * is checked first and the whole script is applied as one unit.
 */
async function applySchema(
  adminUrl: string,
  databaseName: string,
): Promise<void> {
  const client = new Client({
    connectionString: withDatabase(adminUrl, databaseName),
    connectionTimeoutMillis: 10_000,
  });

  await client.connect();

  try {
    if (await hasSchema(client)) return;

    const sql = await readFile(
      path.join(process.cwd(), "src/server/tenancy/schema/001_initial.sql"),
      "utf8",
    );

    // node-postgres sends a multi-command string in an implicit transaction,
    // so a failure part-way leaves no half-applied schema to clean up.
    await client.query(sql);
  } finally {
    await client.end().catch(() => undefined);
  }
}

async function hasSchema(client: Client): Promise<boolean> {
  const marker = await client
    .query<{ version: string }>(
      `SELECT version FROM schema_migrations WHERE version = $1`,
      [TENANT_SCHEMA_VERSION],
    )
    .catch(() => null);

  return marker !== null && marker.rowCount === 1;
}

/**
 * Where a provisioned tenant database actually is.
 *
 * `tenant_databases` stores pointers, never credentials (S-03), but a pointer
 * has to point somewhere real: until the database existed, the row held
 * placeholder text like "pending/us-east-1/acme" and no connection could be
 * opened from it. These are the coordinates of the database this module just
 * created.
 */
export interface ProvisionedConnection {
  readonly host: string;
  readonly port: number;
  readonly username: string;
}

export function provisionedConnection(): ProvisionedConnection | null {
  const adminUrl =
    process.env.TENANT_PROVISIONER_DATABASE_URL ?? process.env.DATABASE_URL;

  if (!adminUrl) return null;

  try {
    const url = new URL(adminUrl);

    return {
      host: url.hostname,
      port: url.port === "" ? 5432 : Number(url.port),
      username: decodeURIComponent(url.username),
    };
  } catch {
    return null;
  }
}

/** Swaps the database name in a connection string, preserving everything else. */
function withDatabase(connectionString: string, databaseName: string): string {
  const url = new URL(connectionString);
  url.pathname = `/${databaseName}`;
  return url.toString();
}
