import "server-only";

import { readFile } from "node:fs/promises";
import path from "node:path";

import { Client } from "pg";

import { migrateTenantDatabase } from "./migrate-tenant";
import { TENANT_BASELINE, TENANT_SCHEMA_VERSION } from "./schema/migrations";

/**
 * Tenant schema version a fully provisioned database is at.
 *
 * Re-exported from `schema/migrations.ts`, which owns the ordered list. It is
 * the version of the *last* migration, not of the baseline: a new database is
 * created from the baseline and then migrated up to here.
 */
export { TENANT_SCHEMA_VERSION };

/** Maintenance database to connect to while creating another one. */
const MAINTENANCE_DATABASE = "postgres";

const SCHEMA_DIRECTORY = "src/server/tenancy/schema";

export type ProvisionDatabaseOutcome =
  | { readonly ok: true; readonly created: boolean }
  | { readonly ok: false; readonly reason: string };

/** What a database already at some schema version is at. */
export interface ExistingSchema {
  readonly version: string;
}

/**
 * Creates a tenant's physical database and applies the tenant schema.
 *
 * This is the one place in the application that talks to Postgres as an
 * administrator rather than as the application. It runs on the *master*
 * server's credentials, which is what makes it able to create a database at
 * all — and why it is deliberately the only module that reads them for this
 * purpose.
 *
 * `CREATE DATABASE` cannot run inside a transaction and cannot run from a
 * connection to the database being created, so this connects to the
 * maintenance database first, then reconnects to the new one to apply the
 * schema. That means the two steps are not atomic: a failure between them
 * leaves an empty database, which the schema step is written to recover from
 * on the next attempt rather than to trip over.
 *
 * In development the tenant databases live on the same server as the master,
 * under the same credentials. A production deployment would point
 * `TENANT_PROVISIONER_DATABASE_URL` at a dedicated server with an account that
 * can create databases and nothing else.
 */
export async function provisionTenantDatabase(
  databaseName: string,
): Promise<ProvisionDatabaseOutcome> {
  if (!isSafeDatabaseName(databaseName)) {
    return { ok: false, reason: `Unsafe database name "${databaseName}".` };
  }

  const adminUrl =
    process.env.TENANT_PROVISIONER_DATABASE_URL ?? process.env.DATABASE_URL;

  if (!adminUrl) {
    return { ok: false, reason: "No provisioner connection is configured." };
  }

  let created = false;

  try {
    created = await createDatabase(adminUrl, databaseName);
    await applySchema(adminUrl, databaseName);

    // The baseline only ever creates the schema as it was at that version.
    // Everything since is applied here, which is also what brings a database
    // provisioned by an older build up to date.
    const migrated = await migrateTenantDatabase(databaseName);

    if (!migrated.ok) {
      return { ok: false, reason: migrated.reason };
    }

    return { ok: true, created };
  } catch (error: unknown) {
    // Never surface the driver error verbatim: it can echo the connection
    // string, credentials included.
    const detail = error instanceof Error ? error.message : "unknown error";
    console.error(
      `Tenant database provisioning failed for "${databaseName}".`,
      detail,
    );
    return { ok: false, reason: detail };
  }
}

/**
 * Guards the one place an identifier reaches SQL as text.
 *
 * `CREATE DATABASE` takes no parameters, so the name is interpolated. It is
 * generated by `deriveDatabaseName` and never user input, but this is the wrong
 * place to rely on that holding forever.
 */
function isSafeDatabaseName(name: string): boolean {
  return /^[a-z_][a-z0-9_]{0,62}$/.test(name);
}

/** True when the database was created, false when it already existed. */
async function createDatabase(
  adminUrl: string,
  databaseName: string,
): Promise<boolean> {
  const client = new Client({
    connectionString: withDatabase(adminUrl, MAINTENANCE_DATABASE),
    connectionTimeoutMillis: 10_000,
  });

  await client.connect();

  try {
    const existing = await client.query(
      "SELECT 1 FROM pg_database WHERE datname = $1",
      [databaseName],
    );

    if (existing.rowCount !== 0) return false;

    // Identifier quoting, not value quoting: the name passed isSafeDatabaseName
    // above, so the quotes are belt to that braces.
    await client.query(`CREATE DATABASE "${databaseName}"`);
    return true;
  } finally {
    await client.end().catch(() => undefined);
  }
}

/**
 * Applies the tenant schema, unless this database already has it.
 *
 * The SQL is generated by Prisma and uses plain `CREATE TABLE`, so running it
 * twice fails. Rather than weaken every statement to IF NOT EXISTS — which
 * would silently accept a half-built database as finished — the version marker
 * is checked first and the whole script is applied as one unit.
 *
 * A database that already has a marker is left alone here; bringing it to the
 * current version is `migrateTenantDatabase`'s job, not this one's.
 */
async function applySchema(
  adminUrl: string,
  databaseName: string,
): Promise<void> {
  const client = new Client({
    connectionString: withDatabase(adminUrl, databaseName),
    connectionTimeoutMillis: 10_000,
  });

  await client.connect();

  try {
    const existing = await existingSchema(client);

    // Already provisioned, at whatever version. Re-running the create script
    // would fail on the first object that already exists, so the baseline is
    // skipped and `migrateTenantDatabase` takes it from here.
    if (existing) return;

    const sql = await readFile(
      path.join(process.cwd(), SCHEMA_DIRECTORY, TENANT_BASELINE.file),
      "utf8",
    );

    // node-postgres sends a multi-command string in an implicit transaction,
    // so a failure part-way leaves no half-applied schema to clean up.
    await client.query(sql);
  } finally {
    await client.end().catch(() => undefined);
  }
}

/**
 * The schema version this database is already at, or null if it has none.
 *
 * Deliberately not "is it at the current version": a database at an older
 * version is provisioned, just outdated, and treating it as empty means
 * re-running create statements against objects that already exist.
 */
async function existingSchema(client: Client): Promise<ExistingSchema | null> {
  const marker = await client
    .query<{ version: string }>(
      `SELECT version FROM schema_migrations ORDER BY applied_at DESC LIMIT 1`,
    )
    .catch(() => null);

  const version = marker?.rows[0]?.version;

  return version === undefined ? null : { version };
}

/**
 * Where a provisioned tenant database actually is.
 *
 * `tenant_databases` stores pointers, never credentials (S-03), but a pointer
 * has to point somewhere real: until the database existed, the row held
 * placeholder text like "pending/us-east-1/acme" and no connection could be
 * opened from it. These are the coordinates of the database this module just
 * created.
 */
export interface ProvisionedConnection {
  readonly host: string;
  readonly port: number;
  readonly username: string;
}

export function provisionedConnection(): ProvisionedConnection | null {
  const adminUrl =
    process.env.TENANT_PROVISIONER_DATABASE_URL ?? process.env.DATABASE_URL;

  if (!adminUrl) return null;

  try {
    const url = new URL(adminUrl);

    return {
      host: url.hostname,
      port: url.port === "" ? 5432 : Number(url.port),
      username: decodeURIComponent(url.username),
    };
  } catch {
    return null;
  }
}

/** Swaps the database name in a connection string, preserving everything else. */
function withDatabase(connectionString: string, databaseName: string): string {
  const url = new URL(connectionString);
  url.pathname = `/${databaseName}`;
  return url.toString();
}
